Agsea modification
MaayanLab/appyter-catalog pull request #764
Opened 2022-03-24 21:22 UTC by lachmann12

I updated the AGSEA to use blitzgsea, and it should run faster now.

2022-03-24 21:57 UTC, u8sand commented
Please update the semiver in `appyter.json`

2022-03-25 15:17 UTC, u8sand requested changes
- [x] testing.ipynb should be removed
- [x] these data files should be removed, if they are somehow necessary they should be put in S3

2022-03-25 15:49 UTC, lachmann12 commented
changes are applied

2022-03-25 17:06 UTC, u8sand approved these changes

2022-03-25 17:07 UTC, merged